spring:
  application:
    name: springaidemo
  ai:
    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta

gemini:
  api:
    key: ${GEMINI_API_KEY}
  ai:
    model: gemini-2.0-flash

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
